### PR TITLE
Added keyboard shortcuts for various actions

### LINKED ISSUE #3: Implement Keyboard Shortcuts for Tools
### Overview
Introduce keyboard shortcuts to expedite tool selection and streamline user interaction within the app.

### Goals
- Enhance user workflow by enabling quick tool access via keyboard shortcuts.
- Improve accessibility and efficiency for users accustomed to shortcut-based navigation.

### Approach
- Assign intuitive and convenient key combinations to essential tools.
- Ensure compatibility across multiple devices and browsers.

### Outcomes
- Accelerated tool selection and usage through keyboard-driven commands.
- Increased user convenience and productivity within the application.

### Note
This enhancement aligns with our commitment to optimizing user interaction and accessibility.

### PR DESCRIPTION
**Pull request by IrfanSalim**
closes #3 

Shortcuts added:

1 - Select rectangle
2 - Select circle
3 - Select triangle
F - Toggle fillcolor
B - Select brush
E - Select eraser
C - Toggle between colors
ALT + C - Clear canvas

### CODE REVIEW

**Comment by IrfanSalim** [comment]
@codewarnab

**Comment by codewarnab** [comment]
> @codewarnab 

Yes I saw the pr i am little busy in exams I will surely review it in 2 days

**Comment by IrfanSalim** [comment]
cool

**Comment by codewarnab** [comment]
> cool

just tested it two short cut isnt working for me `c` and `alt+c` 
if its working on your machine please share a screen video or anything like that

**Comment by IrfanSalim** [comment]
Hey, @codewarnab 

Can you check now, fixed a bug.

**Comment by codewarnab** [comment]
> Hey, @codewarnab
> 
> Can you check now, fixed a bug.

yes seems perfect i am merging it

**Pull request merged**
